# Generated by Django 3.1.7 on 2021-03-17 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exercise',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.user'),
            preserve_default=False,
        ),
    ]
