# Generated by Django 3.1.7 on 2021-03-02 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
