# Generated by Django 3.1.7 on 2021-03-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0003_submission_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='text',
            new_name='code',
        ),
    ]
