# Generated by Django 3.1.7 on 2021-03-04 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0004_auto_20210304_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='added',
            new_name='created',
        ),
    ]
