# Generated by Django 3.1.7 on 2021-03-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0005_auto_20210329_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogress',
            name='completed_questions',
            field=models.ManyToManyField(blank=True, related_name='question_completed_in_exams', to='jsplatform.MultipleChoiceQuestion'),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='current_question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_current_in_exams', to='jsplatform.multiplechoicequestion'),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='currently_serving',
            field=models.CharField(choices=[('q', 'QUESTIONS'), ('e', 'EXERCISES'), ('c', 'ALL COMPLETED')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='initial_item_type',
            field=models.CharField(choices=[('q', 'QUESTIONS'), ('e', 'EXERCISES'), ('c', 'ALL COMPLETED')], default='e', max_length=1),
        ),
    ]
