# Generated by Django 3.1.7 on 2021-03-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0005_auto_20210304_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='has_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
