# Generated by Django 3.1.7 on 2021-03-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0006_auto_20210304_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='has_passed',
            new_name='eligible',
        ),
        migrations.AddField(
            model_name='exercise',
            name='min_passing_testcases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
