# Generated by Django 3.1.7 on 2021-03-10 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0006_auto_20210310_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='assigned_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
