# Generated by Django 3.1.7 on 2021-04-04 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsplatform', '0006_auto_20210329_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='assigned_users',
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='currently_serving',
            field=models.CharField(choices=[('q', 'QUESTIONS'), ('e', 'EXERCISES'), ('c', 'ALL COMPLETED')], default='q', max_length=1),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='jsplatform.exam'),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='initial_item_type',
            field=models.CharField(choices=[('q', 'QUESTIONS'), ('e', 'EXERCISES'), ('c', 'ALL COMPLETED')], default='q', max_length=1),
        ),
        migrations.AlterField(
            model_name='givenanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_answers', to='jsplatform.multiplechoicequestion'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='jsplatform.exam'),
        ),
        migrations.CreateModel(
            name='ExamReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jsplatform.exam')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
