# Generated by Django 3.1.7 on 2021-04-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0008_auto_20210404_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='header',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
