# Generated by Django 3.1.7 on 2021-03-12 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0008_auto_20210310_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='input',
            new_name='assertion',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_exercises', to=settings.AUTH_USER_MODEL),
        ),
    ]
