# Generated by Django 3.1.7 on 2021-03-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0008_auto_20210304_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='is_confirmed',
            new_name='has_been_turned_in',
        ),
    ]
