# Generated by Django 3.1.7 on 2021-03-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0009_auto_20210312_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='starting_code',
            field=models.TextField(blank=True),
        ),
    ]
