# Generated by Django 3.1.7 on 2021-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0010_remove_examreport_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='headers',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
