# Generated by Django 3.1.7 on 2021-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0011_examreport_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
