# Generated by Django 3.1.8 on 2021-04-15 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsplatform', '0014_auto_20210412_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='draft',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='jsplatform.category'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='jsplatform.category'),
        ),
    ]
