# Generated by Django 3.1.8 on 2021-04-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0015_auto_20210415_2227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MultipleChoiceQuestion',
            new_name='Question',
        ),
    ]
