# Generated by Django 3.1.8 on 2021-04-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0016_auto_20210418_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenanswer',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('o', 'OPEN QUESTION'), ('m', 'MULTIPLE CHOICE QUESTION')], default='m', max_length=1),
        ),
    ]
