# Generated by Django 3.1.8 on 2021-04-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0017_auto_20210418_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='introduction_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_aggregated_question',
            field=models.BooleanField(default=False),
        ),
    ]
