# Generated by Django 3.1.8 on 2021-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0018_auto_20210419_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='randomize',
            field=models.BooleanField(default=True),
        ),
    ]
