# Generated by Django 3.1.8 on 2021-04-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0019_category_randomize'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_exercises',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=True),
        ),
    ]
