# Generated by Django 3.1.8 on 2021-04-24 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsplatform', '0021_question_accepts_multiple_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allowed_teachers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_teacher': True}, related_name='exams_referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='exam',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_locked_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
