# Generated by Django 3.1.8 on 2021-04-25 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jsplatform', '0022_auto_20210424_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_closed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
