# Generated by Django 3.1.8 on 2021-06-06 16:16

from django.db import migrations, models
import jsplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0023_auto_20210425_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogress',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to=jsplatform.models.get_pdf_upload_path),
        ),
    ]
