# Generated by Django 3.1.12 on 2021-06-12 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0025_auto_20210612_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogress',
            name='completed_exercises',
            field=models.ManyToManyField(blank=True, related_name='completed_in_exams', through='jsplatform.ExamCompletedExercisesThroughModel', to='jsplatform.Exercise'),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='completed_questions',
            field=models.ManyToManyField(blank=True, related_name='question_completed_in_exams', through='jsplatform.ExamCompletedQuestionsThroughModel', to='jsplatform.Question'),
        ),
    ]
