# Generated by Django 3.1.12 on 2021-06-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0026_auto_20210612_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcompletedexercisesthroughmodel',
            options={'ordering': ['ordering']},
        ),
        migrations.AlterModelOptions(
            name='examcompletedquestionsthroughmodel',
            options={'ordering': ['-ordering']},
        ),
    ]
