# Generated by Django 3.1.12 on 2021-06-12 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0027_auto_20210612_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcompletedquestionsthroughmodel',
            options={'ordering': ['ordering']},
        ),
    ]
