# Generated by Django 3.1.12 on 2021-06-13 22:34

from django.db import migrations, models
import jsplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0029_auto_20210612_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='zip_report_archive',
            field=models.FileField(blank=True, null=True, upload_to=jsplatform.models.get_pdf_upload_path),
        ),
    ]
