# Generated by Django 3.1.12 on 2021-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0030_examreport_zip_report_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['pk'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='question',
            name='rendered_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
