# Generated by Django 3.1.12 on 2021-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0031_auto_20210623_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='rendered_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='rendered_introduction_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='rendered_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
