# Generated by Django 3.1.12 on 2021-06-23 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0032_auto_20210623_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rendered_introduction_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rendered_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
