# Generated by Django 3.1.13 on 2021-07-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0035_auto_20210630_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examcompletedquestionsthroughmodel',
            name='completed_question',
        ),
        migrations.RemoveField(
            model_name='examcompletedquestionsthroughmodel',
            name='exam_progress',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='completed_exercises',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='completed_items_count',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='completed_questions',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='current_category',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='current_exercise',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='current_question',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='currently_serving',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='exhausted_categories',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='initial_item_type',
        ),
        migrations.RemoveField(
            model_name='examprogress',
            name='served_for_current_category',
        ),
        migrations.DeleteModel(
            name='ExamCompletedExercisesThroughModel',
        ),
        migrations.DeleteModel(
            name='ExamCompletedQuestionsThroughModel',
        ),
    ]
