# Generated by Django 3.1.13 on 2021-07-12 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0036_auto_20210712_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogress',
            name='current_item_cursor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExamProgressQuestionsThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField()),
                ('exam_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsplatform.examprogress')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsplatform.question')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ExamProgressExercisesThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField()),
                ('exam_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsplatform.examprogress')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jsplatform.exercise')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.AddField(
            model_name='examprogress',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='completed_in_exams', through='jsplatform.ExamProgressExercisesThroughModel', to='jsplatform.Exercise'),
        ),
        migrations.AddField(
            model_name='examprogress',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='question_completed_in_exams', through='jsplatform.ExamProgressQuestionsThroughModel', to='jsplatform.Question'),
        ),
    ]
