# Generated by Django 3.1.13 on 2021-07-14 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0038_examprogress_is_initialized'),
    ]

    operations = [
        migrations.AddField(
            model_name='examprogress',
            name='begun_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examprogress',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='exercise_assigned_in_exams', through='jsplatform.ExamProgressExercisesThroughModel', to='jsplatform.Exercise'),
        ),
        migrations.AlterField(
            model_name='examprogress',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='question_assigned_in_exams', through='jsplatform.ExamProgressQuestionsThroughModel', to='jsplatform.Question'),
        ),
    ]
