# Generated by Django 3.1.13 on 2021-07-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0039_auto_20210714_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='allow_going_back',
            field=models.BooleanField(default=True),
        ),
    ]
