# Generated by Django 3.1.13 on 2021-07-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0040_exam_allow_going_back'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='givenanswer',
            constraint=models.UniqueConstraint(fields=('user', 'answer_id'), name='same_user_same_answer_unique'),
        ),
    ]
