# Generated by Django 3.1.13 on 2021-07-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0041_auto_20210715_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='selections',
        ),
    ]
