# Generated by Django 3.1.13 on 2021-07-20 15:47

from django.db import migrations, models
import jsplatform.models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0042_remove_answer_selections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examreport',
            name='details',
        ),
        migrations.RemoveField(
            model_name='examreport',
            name='headers',
        ),
        migrations.AddField(
            model_name='examreport',
            name='csv_report',
            field=models.FileField(blank=True, null=True, upload_to=jsplatform.models.get_pdf_upload_path),
        ),
    ]
