# Generated by Django 3.1.13 on 2021-07-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0043_auto_20210720_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
