# Generated by Django 3.1.13 on 2021-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0044_examreport_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='examreport',
            name='generated_reports_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='examreport',
            name='in_progress',
            field=models.BooleanField(default=True),
        ),
    ]
