# Generated by Django 3.1.13 on 2021-07-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0045_auto_20210722_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examreport',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
