# Generated by Django 3.1.13 on 2021-10-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0048_auto_20211022_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='has_been_turned_in',
        ),
    ]
