# Generated by Django 3.1.13 on 2021-10-25 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0049_remove_submission_has_been_turned_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='jsplatform.exercise'),
        ),
    ]
