# Generated by Django 3.1.13 on 2021-10-31 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0050_auto_20211025_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='givenanswer',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
