# Generated by Django 3.1.13 on 2021-11-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0051_givenanswer_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
