# Generated by Django 3.1.13 on 2021-11-17 12:44

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('jsplatform', '0052_exercise_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, prefix='', primary_key=True, serialize=False),
        ),
    ]
